// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKkY59jyLt_XzwKBb4bLPUAc7XfRvG-jI',
    appId: '1:780675515278:web:0462b8932aa02cd86e5adf',
    messagingSenderId: '780675515278',
    projectId: 'svpa-backend',
    authDomain: 'svpa-backend.firebaseapp.com',
    storageBucket: 'svpa-backend.appspot.com',
    measurementId: 'G-161T1M8M49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpg5dbJ_eD03qvtMPfaEvU_S0G6VYyqyc',
    appId: '1:780675515278:android:6105abc8c825677c6e5adf',
    messagingSenderId: '780675515278',
    projectId: 'svpa-backend',
    storageBucket: 'svpa-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXN8PyC7NHfo5iL5_EmkcgiUMA1kHQTY',
    appId: '1:780675515278:ios:234fe9ce6e581b626e5adf',
    messagingSenderId: '780675515278',
    projectId: 'svpa-backend',
    storageBucket: 'svpa-backend.appspot.com',
    androidClientId: '780675515278-8gbie9v4bhqgqdkgl80a6gqite77r9c9.apps.googleusercontent.com',
    iosClientId: '780675515278-8t6opm3eggjiol7373pd1n1bbddaqv8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.svpaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmXN8PyC7NHfo5iL5_EmkcgiUMA1kHQTY',
    appId: '1:780675515278:ios:234fe9ce6e581b626e5adf',
    messagingSenderId: '780675515278',
    projectId: 'svpa-backend',
    storageBucket: 'svpa-backend.appspot.com',
    androidClientId: '780675515278-8gbie9v4bhqgqdkgl80a6gqite77r9c9.apps.googleusercontent.com',
    iosClientId: '780675515278-8t6opm3eggjiol7373pd1n1bbddaqv8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.svpaFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKkY59jyLt_XzwKBb4bLPUAc7XfRvG-jI',
    appId: '1:780675515278:web:ab0f5bb8802a1e6e6e5adf',
    messagingSenderId: '780675515278',
    projectId: 'svpa-backend',
    authDomain: 'svpa-backend.firebaseapp.com',
    storageBucket: 'svpa-backend.appspot.com',
    measurementId: 'G-MKW1ZJHRVC',
  );

}